language:python
python:
  - "3.7"

env:
  - SECRET_KEY='TEST'
services:
  - postgresql
install:
  - pipenv install
script:
  - python manage.py test
#before_script: pip install docker-compose
#script:
#  - docker-compose run app sh -c "python manage.py test && flake8